name: 'Bug Report'
description: Report a bug to help **us** improve **our** software and services.
title: '[BUG] <short description>'
labels: [bug]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## Bug Report
        Please provide a clear and concise description of the problem **you've encountered in our systems or software.**

  - type: textarea
    id: bug-description
    attributes:
      label: Describe the Bug
      description: What went wrong?
      placeholder: 'A clear and concise description of the bug.'
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: List the steps needed for **our team** to reproduce the issue.
      placeholder: |
        1. Run '...'
        2. Call endpoint '...'
        3. Observe error '...'
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen instead?
      placeholder: 'I expected the application/service to ...'
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Screenshots or Logs
      description: Attach screenshots or logs if applicable. **Please ensure no sensitive information is included.**
      placeholder: 'Paste logs or drag-and-drop screenshots here.'

  - type: input
    id: environment
    attributes:
      label: Environment
      description: Describe your setup (OS, Browser, Node.js version, Service/Repo name, etc.)
      placeholder: 'Alma Linux 9, Chrome 120, Node.js 22.x, Service X, etc'
